-- ============================================================
-- FUNDSROUTE - POSTGRESQL DATABASE SCHEMA
-- ============================================================

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE user_status AS ENUM (
    'pending',
    'kyc_pending',
    'verified',
    'rejected',
    'suspended'
);

CREATE TYPE gender_type AS ENUM (
    'male',
    'female',
    'other',
    'prefer_not_to_say'
);

CREATE TYPE kyc_document_type AS ENUM (
    'aadhaar',
    'passport',
    'driving_license',
    'voter_id',
    'other'
);

CREATE TYPE kyc_verification_status AS ENUM (
    'pending',
    'under_review',
    'verified',
    'rejected'
);

CREATE TYPE account_type AS ENUM (
    'savings',
    'current'
);

CREATE TYPE bank_verification_status AS ENUM (
    'pending',
    'verified',
    'rejected'
);

CREATE TYPE transaction_status AS ENUM (
    'draft',
    'pending',
    'processing',
    'completed',
    'failed',
    'cancelled',
    'refunded'
);

-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(30) NOT NULL UNIQUE,

    password_hash VARCHAR(255) NOT NULL,

    status user_status NOT NULL DEFAULT 'pending',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- USER PROFILES
-- ============================================================

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    full_name VARCHAR(150) NOT NULL,

    date_of_birth DATE NOT NULL,

    gender gender_type NOT NULL,

    nationality VARCHAR(100) NOT NULL,

    occupation VARCHAR(100),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_profile_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================================
-- USER CONTACTS
-- ============================================================

CREATE TABLE user_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    email VARCHAR(255) NOT NULL UNIQUE,

    phone VARCHAR(20) NOT NULL UNIQUE,

    email_verified BOOLEAN NOT NULL DEFAULT FALSE,

    phone_verified BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_contact_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================================
-- USER ADDRESSES
-- ============================================================

CREATE TABLE user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    address_line VARCHAR(255) NOT NULL,

    city VARCHAR(100) NOT NULL,

    state VARCHAR(100) NOT NULL,

    country VARCHAR(100) NOT NULL DEFAULT 'India',

    postal_code VARCHAR(20) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================================
-- KYC RECORDS
-- ============================================================

CREATE TABLE kyc_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    document_type kyc_document_type NOT NULL,

    document_number VARCHAR(100) NOT NULL,

    document_file VARCHAR(500),

    selfie_file VARCHAR(500),

    verification_status kyc_verification_status
        NOT NULL DEFAULT 'pending',

    rejection_reason VARCHAR(500),

    submitted_at TIMESTAMP NULL,

    verified_at TIMESTAMP NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_kyc_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================================
-- BANK ACCOUNTS
-- ============================================================

CREATE TABLE bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    account_holder_name VARCHAR(150) NOT NULL,

    bank_name VARCHAR(150) NOT NULL,

    account_number VARCHAR(50) NOT NULL,

    ifsc_code VARCHAR(20) NOT NULL,

    account_type account_type NOT NULL DEFAULT 'savings',

    verification_status bank_verification_status
        NOT NULL DEFAULT 'pending',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_bank_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================================
-- RECIPIENTS
-- ============================================================

CREATE TABLE recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    recipient_name VARCHAR(150) NOT NULL,

    country VARCHAR(100) NOT NULL,

    currency_code CHAR(3) NOT NULL,

    bank_name VARCHAR(150),

    account_holder_name VARCHAR(150),

    account_number VARCHAR(100),

    bank_identifier VARCHAR(50),

    relationship VARCHAR(100),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_recipient_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- ============================================================
-- REMITTANCE TRANSACTIONS
-- ============================================================

CREATE TABLE remittance_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    recipient_id BIGINT NOT NULL,

    transaction_reference VARCHAR(50) NOT NULL UNIQUE,

    source_currency CHAR(3) NOT NULL,

    destination_currency CHAR(3) NOT NULL,

    source_amount DECIMAL(18,2) NOT NULL,

    exchange_rate DECIMAL(18,8) NOT NULL,

    fee_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,

    destination_amount DECIMAL(18,2) NOT NULL,

    status transaction_status NOT NULL DEFAULT 'draft',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transaction_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_transaction_recipient
        FOREIGN KEY (recipient_id)
        REFERENCES recipients(id)
);

-- ============================================================
-- TRANSACTION STATUS HISTORY
-- ============================================================

CREATE TABLE transaction_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    transaction_id BIGINT NOT NULL,

    old_status VARCHAR(30),

    new_status VARCHAR(30) NOT NULL,

    note VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_status_transaction
        FOREIGN KEY (transaction_id)
        REFERENCES remittance_transactions(id)
        ON DELETE CASCADE
);

-- ============================================================
-- UPDATED_AT TRIGGER FUNCTION
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- UPDATED_AT TRIGGERS
-- ============================================================

CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_profiles_updated_at
BEFORE UPDATE ON user_profiles
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_contacts_updated_at
BEFORE UPDATE ON user_contacts
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_addresses_updated_at
BEFORE UPDATE ON user_addresses
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_kyc_records_updated_at
BEFORE UPDATE ON kyc_records
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_bank_accounts_updated_at
BEFORE UPDATE ON bank_accounts
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_recipients_updated_at
BEFORE UPDATE ON recipients
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_remittance_transactions_updated_at
BEFORE UPDATE ON remittance_transactions
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
